name: CI/CD Pipeline

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  ci-cd:
    uses: milsman2/python-app-template/.github/workflows/ci-cd.yaml@v1.19.5
    secrets: inherit
